Split user properties at first occurrence of `=`
When parsing user properties containing `=`, e.g.
`digusers="root,hass,xyz=="` dict conversion fails:

	ValueError: dictionary update sequence element #132 has length 4; 2 is required

This change resolves an error where the event stream initializes but
fails to show events from the camera.

Ref home-assistant/core#36850